[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.dom"]

[phases.install]
cmds = ["echo 'Installing dependencies...'"]

[phases.build]
cmds = [
  "echo 'Building sitemaps...'",
  "php scripts/generate_matrix.php || true",
  "php scripts/generate_career_matrix.php || true",
  "php scripts/build_sitemaps.php || true"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

