<?php
require_once __DIR__ . '/../../templates/head.php';
require_once __DIR__ . '/../../templates/header.php';
require_once __DIR__ . '/../../lib/product_schemas.php';

$GLOBALS['__page_slug'] = 'products/precogs';
$GLOBALS['pageTitle'] = 'Precogs — Ontological Oracle Intelligence Engine | NRLC.ai';
$GLOBALS['pageDesc'] = 'Ontological oracle intelligence engine with predictive reasoning, multi-domain cognition, temporal simulation, and real-time agentic intelligence.';

// Build comprehensive schemas
$productSlug = 'precogs';
$productName = 'Precogs';
$productDescription = 'Ontological oracle intelligence engine with predictive reasoning, multi-domain cognition, temporal simulation, and real-time agentic intelligence.';
$features = [
  'Predictive reasoning',
  'Multi-domain cognition',
  'Ontological structuring',
  'Temporal simulation',
  'Inference from micro-fact streams',
  'Real-time agentic intelligence',
  'Ranking of authority and relevance'
];

$jsonld = array_merge(
  product_universal_schemas($productSlug, $productName, $productDescription),
  product_platform_schemas($productSlug, $productName, $productDescription, $features, 'DeveloperApplication'),
  product_dataset_schemas($productSlug, $productName, $productDescription),
  [product_howto_schema($productSlug, $productName)]
);

$GLOBALS['__jsonld'] = $jsonld;
?>

<main role="main" class="container">
<section class="section">
  <div class="section__content">
    
    <!-- Product Header -->
    <div class="content-block module">
      <div class="content-block__header">
        <h1 class="content-block__title">Precogs</h1>
      </div>
      <div class="content-block__body">
        <p class="lead">Ontological oracle intelligence engine that sits above Croutons.ai, providing predictive reasoning and multi-domain cognition.</p>
        <p>Explore our comprehensive <a href="/services/">AI SEO Services</a> and discover related <a href="/insights/">AI SEO Research & Insights</a>. Learn more about our <a href="/tools/">SEO Tools & Resources</a>.</p>
        <p>Precogs is the "mind" of the system — the reasoning layer that transforms micro-facts into actionable intelligence.</p>
      </div>
    </div>

    <!-- Capabilities -->
    <div class="content-block module">
      <div class="content-block__header">
        <h2 class="content-block__title">Capabilities</h2>
      </div>
      <div class="content-block__body">
        <div class="grid grid-auto-fit">
          <div>
            <h3>Predictive Reasoning</h3>
            <p>Advanced reasoning capabilities that predict outcomes and future states based on ontological relationships and historical patterns.</p>
          </div>
          <div>
            <h3>Multi-Domain Cognition</h3>
            <p>Understanding and reasoning across multiple knowledge domains simultaneously, connecting insights from disparate sources.</p>
          </div>
          <div>
            <h3>Ontological Structuring</h3>
            <p>Building and maintaining complex ontological structures that define entity relationships and semantic hierarchies.</p>
          </div>
          <div>
            <h3>Temporal Simulation</h3>
            <p>Modeling and simulating temporal sequences, predicting how systems evolve over time based on current states.</p>
          </div>
          <div>
            <h3>Inference from Micro-Fact Streams</h3>
            <p>Real-time inference and reasoning from continuous streams of micro-facts generated by Croutons.ai.</p>
          </div>
          <div>
            <h3>Real-Time Agentic Intelligence</h3>
            <p>Providing immediate, actionable intelligence for AI agents making decisions in real-time environments.</p>
          </div>
          <div>
            <h3>Ranking of Authority and Relevance</h3>
            <p>Intelligent ranking systems that assess source authority and content relevance for search and discovery.</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Architecture -->
    <div class="content-block module">
      <div class="content-block__header">
        <h2 class="content-block__title">System Architecture</h2>
      </div>
      <div class="content-block__body">
        <p>Precogs operates as the reasoning layer above Croutons.ai's fact layer. It consumes micro-facts, applies ontological reasoning, and generates predictive insights. This architecture enables:</p>
        <ul>
          <li>Complex multi-step reasoning across domains</li>
          <li>Predictive modeling based on historical patterns</li>
          <li>Real-time decision support for AI agents</li>
          <li>Authority and relevance scoring for content</li>
          <li>Temporal reasoning and future state prediction</li>
        </ul>
      </div>
    </div>

    <div class="content-block module">
      <div class="content-block__body">
        <div class="btn-group text-center">
          <a href="/products/" class="btn">View All Products</a>
        </div>
      </div>
    </div>

  </div>
    <!-- Related Resources -->
    <div class="content-block module">
      <div class="content-block__header">
        <h2 class="content-block__title">Related Resources</h2>
      </div>
      <div class="content-block__body">
        <p>Explore our comprehensive <a href="/services/">AI SEO Services</a> including <a href="/services/crawl-clarity/">Crawl Clarity Engineering</a> for technical SEO optimization.</p>
        <p>Discover our latest <a href="/insights/">AI SEO Research & Insights</a> including the <a href="/insights/geo16-introduction/">GEO-16 Framework</a> for AI citation optimization.</p>
        <p>Browse our <a href="/tools/">SEO Tools & Resources</a> and view all <a href="/products/">Products</a>.</p>
        <div class="btn-group text-center">
          <a href="/services/" class="btn btn--primary">Get Started with AI SEO</a>
        </div>
      </div>
    </div>
</section>
</main>


