<?php
// Failure Modes Index
// Layer 3: Master index for all failure patterns

if (!function_exists('webpage_schema')) {
  require_once __DIR__.'/../../../lib/schema_builders.php';
}

$canonicalUrl = absolute_url('/generative-engine-optimization/failure-modes/');

$failureModes = [
  [
    'slug' => 'canonical-drift',
    'name' => 'Canonical Drift',
    'description' => 'Multiple URLs serve the same content, causing retrieval confusion and confidence loss.'
  ],
  [
    'slug' => 'schema-noise',
    'name' => 'Schema Noise',
    'description' => 'Conflicting or excessive structured data reduces confidence and citation eligibility.'
  ],
  [
    'slug' => 'faceted-navigation',
    'name' => 'Faceted Navigation',
    'description' => 'Dynamic URLs create duplicate content signals that fragment retrieval confidence.'
  ],
  [
    'slug' => 'ai-content-collapse',
    'name' => 'AI Content Collapse',
    'description' => 'Content generated by AI without human verification loses trust and retrieval probability.'
  ],
  [
    'slug' => 'conflicting-entities',
    'name' => 'Conflicting Entities',
    'description' => 'Multiple entity definitions for the same concept create ambiguity and reduce confidence.'
  ]
];

$GLOBALS['__jsonld'] = [
  // About / Entity Graph
  [
    '@context' => 'https://schema.org',
    '@graph' => [
      [
        '@type' => 'Organization',
        '@id' => absolute_url('/') . '#organization',
        'name' => 'Neural Command LLC',
        'url' => absolute_url('/'),
        'logo' => [
          '@type' => 'ImageObject',
          '@id' => absolute_url('/') . '#logo',
          'url' => absolute_url('/logo.png')
        ],
        'sameAs' => [
          'https://www.linkedin.com/company/neural-command/'
        ]
      ]
    ]
  ],
  // BreadcrumbList
  [
    '@context' => 'https://schema.org',
    '@type' => 'BreadcrumbList',
    '@id' => $canonicalUrl . '#breadcrumb',
    'itemListElement' => [
      [
        '@type' => 'ListItem',
        'position' => 1,
        'name' => 'Home',
        'item' => absolute_url('/')
      ],
      [
        '@type' => 'ListItem',
        'position' => 2,
        'name' => 'Generative Engine Optimization',
        'item' => absolute_url('/generative-engine-optimization/')
      ],
      [
        '@type' => 'ListItem',
        'position' => 3,
        'name' => 'Failure Modes',
        'item' => $canonicalUrl
      ]
    ]
  ],
  // CollectionPage
  [
    '@context' => 'https://schema.org',
    '@type' => 'CollectionPage',
    '@id' => $canonicalUrl . '#page',
    'headline' => 'GEO Failure Modes',
    'name' => 'GEO Failure Modes Index',
    'description' => 'Observable failure patterns that cause content to disappear from AI-generated answers. Each failure mode documents mechanics, triggers, and mitigation strategies.',
    'url' => $canonicalUrl,
    'about' => [
      '@type' => 'DefinedTerm',
      'name' => 'GEO Failure Modes',
      'description' => 'Patterns that cause content to lose retrieval confidence and citation eligibility in generative engines.'
    ]
  ]
];
?>

<main role="main" class="container">
  <section class="section">
    <div class="section__content">
      
      <!-- Back Link -->
      <div class="content-block module" style="margin-bottom: var(--spacing-md);">
        <div class="content-block__body">
          <p><a href="/generative-engine-optimization/" class="btn btn--secondary">← Back to GEO Overview</a></p>
        </div>
      </div>

      <!-- Hero Block -->
      <div class="content-block module">
        <div class="content-block__header">
          <h1 class="content-block__title heading-1">GEO Failure Modes</h1>
        </div>
        <div class="content-block__body">
          <p class="lead text-lg">Observable failure patterns that cause content to disappear from AI-generated answers</p>
          <div class="callout-system-truth">
            <p>
              LLMs learn better from negative constraints than from advice. This index documents why content fails retrieval, not how to succeed.
            </p>
          </div>
        </div>
      </div>

      <!-- Failure Modes List -->
      <div class="content-block module">
        <div class="content-block__header">
          <h2 class="content-block__title heading-2">Failure Mode Index</h2>
        </div>
        <div class="content-block__body">
          <p>Each failure mode follows a fixed template:</p>
          <ol>
            <li>Failure Name</li>
            <li>What the Model Sees</li>
            <li>Why Confidence Drops</li>
            <li>What Gets Ignored</li>
            <li>Common Triggers</li>
            <li>Observed Outcomes</li>
            <li>Mitigation Strategy</li>
          </ol>
          <p>No opinions. No tips. Only mechanics.</p>
        </div>
      </div>

      <!-- Failure Modes Grid -->
      <div class="content-block module">
        <div class="content-block__body">
          <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: var(--spacing-md);">
            <?php foreach ($failureModes as $mode): ?>
              <div style="padding: var(--spacing-md); border: 1px solid var(--color-border, #ddd); border-radius: 4px;">
                <h3 class="heading-3" style="margin-top: 0;">
                  <a href="/generative-engine-optimization/failure-modes/<?= htmlspecialchars($mode['slug']) ?>/">
                    <?= htmlspecialchars($mode['name']) ?>
                  </a>
                </h3>
                <p><?= htmlspecialchars($mode['description']) ?></p>
                <p><a href="/generative-engine-optimization/failure-modes/<?= htmlspecialchars($mode['slug']) ?>/">Read failure mode →</a></p>
              </div>
            <?php endforeach; ?>
          </div>
        </div>
      </div>

      <!-- Why This Matters -->
      <div class="content-block module">
        <div class="content-block__header">
          <h2 class="content-block__title heading-2">Why Failure Modes Dominate Citations</h2>
        </div>
        <div class="content-block__body">
          <p>When an LLM answers:</p>
          <ul>
            <li>"Why isn't my site showing up in AI results?"</li>
            <li>"Why does schema stop working?"</li>
            <li>"Why does content disappear from AI Overviews?"</li>
          </ul>
          <p>It needs deterministic explanations of failure mechanics, not success tips.</p>
          <p>This index becomes the reference library for "why content disappears."</p>
          <p><a href="/generative-engine-optimization/">Learn more about GEO →</a></p>
        </div>
      </div>

    </div>
  </section>
</main>

